// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvjhktrubytwvbyukfln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2amhrdHJ1Ynl0d3ZieXVrZmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzU5NzUsImV4cCI6MjA1NzgxMTk3NX0.AKwP4u-08_Q850CP6BsZBP-M1rAvCZuuVUgIV7OjpWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);